#!/usr/bin/env python3
"""Convert the real public datasets in data/raw/real/ into committed, contract-compliant files.

Outputs (all small enough to commit, each folder carries a LICENSE with attribution):
  data/real/polygon_news/polygon_news.csv   InputRecord news CSV (all 5,548 Polygon articles, MIT)
  data/real/polygon_news/silver_labels.csv  ticker-level LLM sentiment insights (never fed to engine)
  data/real/stock_tweets/sample.csv         InputRecord social CSV (stratified sample, CC0)
  data/real/stock_tweets/outcomes.csv       forward returns / volatility / polarity per record
  data/real/gdelt/snapshot.csv              finance-relevant GDELT GKG headlines (2 h snapshot)
  data/train/hf_fin_topic/*.csv             event-classifier train/valid split (MIT)
  data/train/hf_fin_sentiment/*.csv         sentiment train/valid split (MIT)
  data/train/phrasebank/sample.csv          stratified PhraseBank sample (CC BY-NC-SA 3.0)

Usage: uv run python scripts/data/convert_real.py [--tweets 5000] [--phrasebank 600]
"""

import argparse
import csv
import hashlib
import html
import importlib.util
import json
import re
import shutil
import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
RAW = REPO_ROOT / "data" / "raw" / "real"
REAL = REPO_ROOT / "data" / "real"
TRAIN = REPO_ROOT / "data" / "train"

_spec = importlib.util.spec_from_file_location(
    "build_manifest", Path(__file__).with_name("build_manifest.py")
)
build_manifest = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(build_manifest)

NEWS_COLS = [
    "record_id", "source_id", "source_type", "headline", "body", "published_at",
    "timestamp_quality", "simulated_at", "is_synthetic", "primary_entity_id",
]  # fmt: skip
SOCIAL_COLS = [
    "record_id", "source_id", "source_type", "text", "author_handle", "published_at",
    "timestamp_quality", "simulated_at", "is_synthetic", "cashtags", "primary_entity_id",
]  # fmt: skip

LICENSES = {
    "polygon_news": (
        "MIT",
        "Polygon.io financial news with ticker-level sentiment insights, published on Kaggle as\n"
        "rdolphin/financial-news-with-ticker-level-sentiment (license: MIT, per the Kaggle API).\n"
        "Ticker-level sentiment insights are LLM-generated by the publisher: treat them as silver\n"
        "labels, not human ground truth.\n",
    ),
    "stock_tweets": (
        "CC0-1.0",
        "Tweets with stock returns, published on Kaggle as\n"
        "thedevastator/tweet-sentiment-s-impact-on-stock-returns (license: CC0, per the Kaggle API).\n"
        "Tweet text originates from X/Twitter and remains subject to its terms; only a sample is\n"
        "committed. LSTM/TextBlob polarity columns are model outputs (silver labels).\n",
    ),
    "gdelt": (
        "GDELT open data (attribution required)",
        "Headlines and metadata from the GDELT Project 2.0 Global Knowledge Graph 15-minute files\n"
        "(http://data.gdeltproject.org/gdeltv2/). GDELT data is free and open; cite\n"
        "'The GDELT Project (https://www.gdeltproject.org/)'. Headlines remain the property of\n"
        "their publishers; only titles and URLs are stored.\n",
    ),
    "hf_fin_topic": (
        "MIT",
        "zeroshot/twitter-financial-news-topic (Hugging Face), released under the MIT License.\n",
    ),
    "hf_fin_sentiment": (
        "MIT",
        "zeroshot/twitter-financial-news-sentiment (Hugging Face), released under the MIT License.\n",
    ),
    "phrasebank": (
        "CC BY-NC-SA 3.0",
        "FinancialPhraseBank v1.0. Malo, P., Sinha, A., Korhonen, P., Wallenius, J. and Takala, P.\n"
        "(2014) 'Good debt or bad debt: Detecting semantic orientations in economic texts', JASIST\n"
        "65(4). Licensed under Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported\n"
        "(bundled License.txt; the Kaggle mirror ankurzing/sentiment-analysis-for-financial-news\n"
        "lists CC BY-NC-SA 4.0). This sample stays under that license and is NOT relicensed as MIT.\n"
        "FinBERT was fine-tuned on PhraseBank: never report it as an independent benchmark.\n",
    ),
}


def rid(prefix: str, *parts: object) -> str:
    digest = hashlib.sha1("|".join(map(str, parts)).encode()).hexdigest()[:12]
    return f"{prefix}-{digest}"


def write_license(folder: Path, key: str) -> None:
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "LICENSE").write_text(LICENSES[key][1])


def register(path: Path, description: str, key: str, source: str, columns=None) -> None:
    build_manifest.register_dataset(
        str(path.relative_to(REPO_ROOT)),
        description,
        LICENSES[key][0],
        is_synthetic=False,
        source=source,
        columns=columns,
    )


def polygon() -> int:
    arts = json.loads((RAW / "polygon_news" / "polygon_news_sample.json").read_text())
    out_dir = REAL / "polygon_news"
    write_license(out_dir, "polygon_news")
    rows, silver = [], []
    for a in sorted(arts, key=lambda a: (a["published_utc"], a["id"])):
        record_id = rid("pg", a["id"])
        rows.append(
            {
                "record_id": record_id,
                "source_id": "kaggle_rdolphin_polygon_news",
                "source_type": "news",
                "headline": a["title"].strip(),
                "body": (a.get("description") or "").strip(),
                "published_at": a["published_utc"],
                "timestamp_quality": "original",
                "simulated_at": "",
                "is_synthetic": "false",
                "primary_entity_id": "",  # no hint: the entity linker must find the company
            }
        )
        for ins in a.get("insights") or []:
            silver.append(
                {
                    "record_id": record_id,
                    "ticker": ins.get("ticker"),
                    "sentiment": ins.get("sentiment"),
                    "label_source": "polygon_llm_insight",
                }
            )
        for t in a.get("tickers") or []:
            silver.append(
                {
                    "record_id": record_id,
                    "ticker": t,
                    "sentiment": "",
                    "label_source": "polygon_tickers",
                }
            )
    news_path, silver_path = out_dir / "polygon_news.csv", out_dir / "silver_labels.csv"
    pd.DataFrame(rows, columns=NEWS_COLS).to_csv(news_path, index=False)
    pd.DataFrame(silver).to_csv(silver_path, index=False)
    src = "https://www.kaggle.com/datasets/rdolphin/financial-news-with-ticker-level-sentiment"
    register(
        news_path,
        "Real 2023 Polygon.io financial news (title + description), news replay feed",
        "polygon_news",
        src,
        NEWS_COLS,
    )
    register(
        silver_path,
        "Polygon tickers[] and LLM ticker-level sentiment (silver labels, eval only)",
        "polygon_news",
        src,
    )
    return len(rows)


def tweets(n: int) -> int:
    raw = RAW / "stock_tweets" / "full_dataset-release.csv"
    tw = pd.read_csv(raw, engine="python", on_bad_lines="skip")
    ok_date = tw.DATE.astype(str).str.fullmatch(r"\d\d/\d\d/\d{4}")
    tw = tw[ok_date & (tw.TWEET.astype(str).str.strip().str.len() >= 20)].copy()
    tw = tw.drop_duplicates("TWEET")
    # Stratify across the 25 most-covered companies so the sample supports Module A
    top = tw.STOCK.value_counts().head(25).index
    tw = tw[tw.STOCK.isin(top)]
    per = max(1, n // len(top))
    tw = tw.sample(frac=1.0, random_state=42).groupby("STOCK").head(per)
    tw["published_at"] = pd.to_datetime(tw.DATE, format="%d/%m/%Y").dt.strftime(
        "%Y-%m-%dT00:00:00Z"
    )
    tw = tw.sort_values(["published_at", "TWEET"])
    tw["record_id"] = [rid("tw", s, d, t) for s, d, t in zip(tw.STOCK, tw.DATE, tw.TWEET)]
    tw["cashtags"] = tw.TWEET.astype(str).map(
        lambda t: ",".join(sorted(set(re.findall(r"\$[A-Za-z]{1,6}\b", t))))
    )
    social = pd.DataFrame(
        {
            "record_id": tw.record_id,
            "source_id": "kaggle_thedevastator_stock_tweets",
            "source_type": "social",
            "text": tw.TWEET.astype(str).str.strip(),
            "author_handle": "",
            "published_at": tw.published_at,
            "timestamp_quality": "date_only",
            "simulated_at": "",
            "is_synthetic": "false",
            "cashtags": tw.cashtags,
            "primary_entity_id": "",
        }
    )
    out_dir = REAL / "stock_tweets"
    write_license(out_dir, "stock_tweets")
    sample_path, outcome_path = out_dir / "sample.csv", out_dir / "outcomes.csv"
    social[SOCIAL_COLS].to_csv(sample_path, index=False)
    keep = ["record_id", "STOCK", "LAST_PRICE", "1_DAY_RETURN", "3_DAY_RETURN", "7_DAY_RETURN",
            "VOLATILITY_10D", "VOLATILITY_30D", "TEXTBLOB_POLARITY", "LSTM_POLARITY"]  # fmt: skip
    tw[keep].to_csv(outcome_path, index=False)
    src = "https://www.kaggle.com/datasets/thedevastator/tweet-sentiment-s-impact-on-stock-returns"
    register(
        sample_path,
        f"Real 2017-2018 stock tweets, {len(social)}-row sample across 25 companies, social replay feed",
        "stock_tweets",
        src,
        SOCIAL_COLS,
    )
    register(
        outcome_path,
        "Forward 1/3/7-day returns, volatility and model polarity for the tweet sample",
        "stock_tweets",
        src,
    )
    return len(social)


GKG_FINANCE_THEMES = re.compile(
    r"\b(ECON_|EPU_|WB_\d+_(FINANC|BANK|DEBT|TRADE)|TAX_|SANCTIONS|CYBER_ATTACK|STRIKE|BANKRUPTCY)"
)


def parse_gkg_rows(lines) -> list:
    """Map GDELT GKG 2.1 tab-separated rows to InputRecord news rows (finance-relevant only)."""
    rows = []
    for g in csv.reader(lines, delimiter="\t"):
        if len(g) < 27 or not GKG_FINANCE_THEMES.search(g[7]):
            continue
        m = re.search(r"<PAGE_TITLE>(.*?)</PAGE_TITLE>", g[26])
        if not m:
            continue
        title = html.unescape(m.group(1)).strip()
        if len(title) < 25:
            continue
        ts = pd.to_datetime(g[1], format="%Y%m%d%H%M%S").strftime("%Y-%m-%dT%H:%M:%SZ")
        rows.append(
            {
                "record_id": rid("gd", g[0]),
                "source_id": "gdelt_gkg_v2",
                "source_type": "news",
                "headline": title,
                "body": "",  # GKG carries no article text; never feed themes/URL to the classifier
                "published_at": ts,
                "timestamp_quality": "original",
                "simulated_at": "",
                "is_synthetic": "false",
                "primary_entity_id": "",
                "source_url": g[4],
            }
        )
    return rows


def gdelt() -> int:
    csv.field_size_limit(sys.maxsize)
    rows = []
    for f in sorted((RAW / "gdelt").glob("*.gkg.csv")):
        with open(f, encoding="utf-8", errors="replace") as fh:
            rows.extend(parse_gkg_rows(fh))
    df = pd.DataFrame(rows).drop_duplicates("headline").sort_values(["published_at", "record_id"])
    out_dir = REAL / "gdelt"
    write_license(out_dir, "gdelt")
    path = out_dir / "snapshot.csv"
    df[NEWS_COLS + ["source_url"]].to_csv(path, index=False)
    register(
        path,
        "Real GDELT 2.0 GKG finance-relevant headlines, recorded 2-hour live snapshot",
        "gdelt",
        "http://data.gdeltproject.org/gdeltv2/",
        NEWS_COLS + ["source_url"],
    )
    return len(df)


def hf_splits() -> int:
    n = 0
    for key, files in {"hf_fin_topic": ("topic_train.csv", "topic_valid.csv"),
                       "hf_fin_sentiment": ("sent_train.csv", "sent_valid.csv")}.items():  # fmt: skip
        out_dir = TRAIN / key
        write_license(out_dir, key)
        for name in files:
            dst = out_dir / name
            shutil.copy2(RAW / key / name, dst)
            n += len(pd.read_csv(dst))
            repo = "zeroshot/twitter-financial-news-" + ("topic" if "topic" in key else "sentiment")
            register(
                dst,
                f"{repo} {name.split('_')[1].removesuffix('.csv')} split (real labeled financial tweets)",
                key,
                f"https://huggingface.co/datasets/{repo}",
                ["text", "label"],
            )
    return n


def phrasebank(n: int) -> int:
    pb = pd.read_csv(
        RAW / "phrasebank" / "all-data.csv",
        header=None,
        names=["label", "text"],
        encoding="latin-1",
    )
    sample = pb.groupby("label").sample(frac=n / len(pb), random_state=42)
    sample.insert(0, "record_id", [rid("pb", t) for t in sample.text])
    out_dir = TRAIN / "phrasebank"
    write_license(out_dir, "phrasebank")
    path = out_dir / "sample.csv"
    sample.to_csv(path, index=False)
    register(
        path,
        f"FinancialPhraseBank stratified {len(sample)}-row sample (sentiment training augmentation only)",
        "phrasebank",
        "https://www.kaggle.com/datasets/ankurzing/sentiment-analysis-for-financial-news",
        ["record_id", "label", "text"],
    )
    return len(sample)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tweets", type=int, default=5000)
    ap.add_argument("--phrasebank", type=int, default=600)
    args = ap.parse_args()
    if not RAW.exists():
        sys.exit("data/raw/real/ not found: run scripts/data/fetch_real.py first")
    print("polygon news:", polygon())
    print("stock tweets:", tweets(args.tweets))
    print("gdelt snapshot:", gdelt())
    print("hf splits rows:", hf_splits())
    print("phrasebank sample:", phrasebank(args.phrasebank))
